Fixed 'mctp-error-detection' returning false alarms for GPU/NVSwitch/PCIeSwitch0. Fixes nvbug https://nvbugswb.nvidia.com/NVBugs5/redir.aspx?url=/3660110

diff --git a/tools/mctp-error-detection b/tools/mctp-error-detection
--- a/tools/mctp-error-detection
+++ b/tools/mctp-error-detection
@@ -35,17 +35,31 @@ if [ $# -ne 1 ]; then
 fi
 
 cmdline="busctl call xyz.openbmc_project.GpuMgr /xyz/openbmc_project/GpuMgr xyz.openbmc_project.GpuMgr.Server PassthroughFpga iyyyau 0 0xb1 0x81 0 0"
-# Sample Output: (iau) 0 4 0 520126897 0 0
+
+# Sample Output: (iau) 0 4 0 520126897 8 0
+# Indexes:         1   2 3 4  5        6 7
+# Index Meaning:
+#          1 signature
+#          2 dBus return code
+#          3 size from array of words (words of 64 bits)
+#          4 array[0] = return code from PassthroughFpga
+#          5 array[1] = states
+#          6 array[2] = data output
+#          7 array[3] = extended data
 
 if [ "$DRY_RUN" -eq 1 ]; then
     echo $cmdline
     return 0
 fi
 
-output=`$cmdline`;rc=$?
+#output="(iau) 0 4 0 520126897 5091 0"
+#echo $output
+
+output=`$cmdline`
+rc=$?
 [ "$rc" -eq 0 ] || return $rc
-# Cut on delimiter ' ' to get 5 index = 520126897
-output=`echo $output | cut -d ' ' -f 5`
+# Cut on delimiter ' ' to get 6 index, the data output
+output=`echo $output | cut -d ' ' -f 6`
 
 case $1 in
 
