Update xid-event-util-wrapper for platforms with varying GPU index and prefix requirements
Updating the xid-event-util-wrapper script so that it can accomodate platforms with GPU device names without the HGX_ prefix and GPU modules that start at index 0.

Testing:
Loaded test firmware onto LegoCg1, injected sm_fault_trigger through NVRastool, observed that XID events can be generated.  Also checked that the nvidia-xid-event-handler.service did not exit due to any errors.

Fixes NVBUG https://nvbugspro.nvidia.com/bug/4489317

Signed-off-by: Howard Tang <howardt@nvidia.com>

diff --git a/tools/xid-event-util-wrapper b/tools/xid-event-util-wrapper
--- a/tools/xid-event-util-wrapper
+++ b/tools/xid-event-util-wrapper
@@ -5,20 +5,20 @@ set -o pipefail
 APP_NAME="xid-event-util-wrapper"
 APP_VER="1.0"
 
-[ -z "$DEVICE_NAME_PREFIX" ] && DEVICE_NAME_PREFIX="HGX_"
-
 show_help()
 {
     echo "A wrapper for xid events for GPUs and NVSwitches, ver=${APP_VER}."
     echo "<usage>"
-    echo "  ${APP_NAME} [--dry-run] <device_id> <oob_property> <xid_data>"
-    echo "  ${APP_NAME} [--dry-run] --test-event-log <device_id> <oob_property> <xid_data>"
+    echo "  ${APP_NAME} [--dry-run] <device_id> <platform_device_id> <oob_property> <xid_data>"
+    echo "  ${APP_NAME} [--dry-run] --test-event-log <device_id> <platform_device_id> <oob_property> <xid_data>"
     echo "  ${APP_NAME} [--dry-run] --monitor-from-file <file_name>"
     echo
     echo "<options>"
     echo "  --dry-run           - Only print ${APP_NAME} cmdline."
     echo
-    echo "  device_id           - Device ID: For NVSwitch->NVSwitch_[0-3], For GPU->GPU_SXM_[1-8]"
+    echo "  device_id           - Device ID: Common device ID, in form of [DeviceType]_[DeviceID].  For example NVSwitch_2 or GPU_7"
+    echo
+    echo "  platform_device_id  - Platform Device ID: Device ID on platform level used to identify module in Redfish or DBus. For example HGX_GPU_SXM_1."
     echo
     echo "  oob_property        - OOB properties Supported: gpu.xid.event, nvswitch.Sxid.event"
     echo
@@ -80,6 +80,10 @@ function createLog()
 {
   xid="_XID"
   msg_arg="$1"
+  # Cut out any prefixes that came with the platform name for use in the logs.  For example, for platform device name
+  # HGX_GPU_SXM_1, we want the log name to be GPU_SXM_1, cutting out everything before the device type, which in this
+  # case is "GPU".
+  device_log_name=$(echo ${platform_device_name} | awk -F\\${device_type} -v dev=${device_type} '{print dev$2}')
   # Replace "," with ";" from all the XID messages
   # "," are used to split message args, "," in a XID Message would increase the MessageArgs count to be greater than 2
   msg_arg=${msg_arg//,/;}
@@ -90,12 +94,12 @@ function createLog()
   busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging xyz.openbmc_project.Logging.Create Create ssa{ss} \""$event" Error\"
   \"xyz.openbmc_project.Logging.Entry.Level.Critical\" 7
   \"xyz.openbmc_project.Logging.Entry.Resolution\" \"Regarding XID documentation and further actions please refer to https://docs.nvidia.com/deploy/xid-errors/index.html\"
-  \"REDFISH_MESSAGE_ARGS\" \""$deviceName" Driver Event Message, "$msg_arg"\"
+  \"REDFISH_MESSAGE_ARGS\" \""${device_log_name}" Driver Event Message, "$msg_arg"\"
   \"REDFISH_MESSAGE_ID\" \"ResourceEvent.1.0.ResourceErrorsDetected\"
-  \"namespace\" \"${deviceName}${xid}\"
+  \"namespace\" \"${device_log_name}${xid}\"
   \"EVENT_NAME\" \"$event\"
-  \"DEVICE_NAME\" \"$deviceName\"
-  \"REDFISH_ORIGIN_OF_CONDITION\" \"/xyz/openbmc_project/inventory/system/chassis/${DEVICE_NAME_PREFIX}${deviceName}\"
+  \"DEVICE_NAME\" \"${device_log_name}\"
+  \"REDFISH_ORIGIN_OF_CONDITION\" \"/xyz/openbmc_project/inventory/system/chassis/${platform_device_name}\"
   "
 
   if [ $DRY_RUN -eq 1 ]; then
@@ -126,7 +130,7 @@ function convertHexToAscii()
 
 function readEventsPendingRegisterProperty()
 {
-  local pendingRegisterOut=$(busctl get-property xyz.openbmc_project.GpuMgr "/xyz/openbmc_project/inventory/system/chassis/$DEVICE_NAME_PREFIX$deviceName" xyz.openbmc_project.com.nvidia.Events.PendingRegister EventsPendingRegister)
+  local pendingRegisterOut=$(busctl get-property xyz.openbmc_project.GpuMgr "/xyz/openbmc_project/inventory/system/chassis/${platform_device_name}" xyz.openbmc_project.com.nvidia.Events.PendingRegister EventsPendingRegister)
   local pendingRegister=$(echo "$pendingRegisterOut" | awk '{print $2}')
   if [ -z "$pendingRegister" ];then
     echo $pendingRegisterOut
@@ -150,10 +154,44 @@ function readEventsPendingRegisterCoreAPI()
   return 0
 }
 
+function set_globals()
+{
+  # Global variables based on input information, used by other functions
+
+  # From the Common Device ID, derive the device type ie GPU or NVSwitch
+  # and the Device ID, which is 0-based
+  device_type=$(echo "$1" | cut -d '_' -f 1)
+  device_id=$(echo "$1" | grep -Eo '[0-9]+$')
+
+  platform_device_name=$2
+  gpumgr_property=$3
+  gpumgr_opcode=$4
+
+  if [ -z ${device_id} ] || [ -z ${device_type} ]; then
+    echo "Unsupported device $1. Exiting!"
+    show_help
+    return 1
+  fi
+
+  if [[ ${device_type} == "GPU" ]]; then
+    event="XID"
+    eventsPendingProp="gpu.events.PendingRegister"
+  elif [[ ${device_type} == "NVSwitch" ]]; then
+    event="SXID"
+    eventsPendingProp="nvswitch.events.PendingRegister"
+  else
+    echo "Unsupported device type ${device_type}. Exiting!"
+    show_help
+    return 1
+  fi
+
+  return 0
+}
+
 # function
 function main()
 {
-  if [ $# -ne 3 ]; then
+  if [ $# -ne 4 ]; then
     show_help
     return 1
   fi
@@ -163,33 +201,15 @@ function main()
   local demFailCounter=0
   local maxDemFailCounter=20
 
-  # these are not locals, they are used by other functions
-  deviceName=$1
-  device=$(echo "$1" | grep -Eo '[0-9]+$')
-
-  if [ -z $device ]; then
-    echo "Invalid Device $1. Exiting!"
-    show_help
+  # Set some global variables such as device name and type based on input
+  set_globals "$@"
+  local set_globals_rc=$?
+  if [ "$set_globals_rc" -ne 0 ]; then
+    echo "Failed to set device variables for device $1. Exiting!"
     return 1
   fi
 
-  if [[ $1 == *"GPU"* ]]; then
-    device_id=$(($device-1))
-    event="XID"
-    eventsPendingProp="gpu.events.PendingRegister"
-  else
-    device_id=$device
-    event="SXID"
-    eventsPendingProp="nvswitch.events.PendingRegister"
-  fi
-
-  if [ -z $device_id ] || [ $device_id -eq -1 ]; then
-    echo "Unsupported GPU Device $device_id. Exiting!"
-    show_help
-    return 1
-  fi
-
-  cmdline="busctl call xyz.openbmc_project.GpuMgr /xyz/openbmc_project/GpuMgr xyz.openbmc_project.GpuMgr.Server DeviceGetData isi $device_id \"$2\" 1"
+  cmdline="busctl call xyz.openbmc_project.GpuMgr /xyz/openbmc_project/GpuMgr xyz.openbmc_project.GpuMgr.Server DeviceGetData isi ${device_id} \"${gpumgr_property}\" 1"
 
   if [ "$DRY_RUN" -eq 1 ]; then
       echo $cmdline
@@ -219,7 +239,7 @@ function main()
   while [ $eventPendingRegister -ne 0 ]
   do
     # Check for the arguments
-    case $3 in
+    case ${gpumgr_opcode} in
 
       XidId)
 
@@ -333,12 +353,13 @@ function monitor_main()
   for device_string in $devices_to_check; do
     #echo "$device_string"
     local devname=$(echo "$device_string" | cut -f1 -d,)
-    local propname=$(echo "$device_string" | cut -f2 -d,)
-    local opcode=$(echo "$device_string" | cut -f3 -d,)
-    main "$devname" "$propname" "$opcode"
+    local platformdevname=$(echo "$device_string" | cut -f2 -d,)
+    local propname=$(echo "$device_string" | cut -f3 -d,)
+    local opcode=$(echo "$device_string" | cut -f4 -d,)
+    main "$devname" "$platformdevname" "$propname" "$opcode"
     local device_rc=$?
     if [ "$device_rc" -ne 0 ]; then
-      >&2 echo "<3>Error: check for [$devname $propname $opcode] failed, rc=$device_rc"
+      >&2 echo "<3>Error: check for [$devname $platformdevname $propname $opcode] failed, rc=$device_rc"
       failed_device_rc=$device_rc
     fi
   done
@@ -356,7 +377,7 @@ function monitor_main()
 
 function test_event_creation_notfication()
 {
-   deviceName=$1
+   set_globals "$@"
    local XidTime="Sun Apr 12 12:47:07 UTC 1970"
    local XidSeqNum="10944768"
    local XidFlags="00"
@@ -365,6 +386,7 @@ function test_event_creation_notfication()
    local ascii="dCh 00000008"
    local result="[$XidTime][$XidSeqNum][$XidFlags] $event $XidId $ascii"
    createLog "$result"
+   return $?
 }
 
 
@@ -381,7 +403,11 @@ fi
 if [ "$1" = "--test-event-log" ]; then
    shift
    test_event_creation_notfication "$@"
-   exit 0
+   test_event_creation_rc=$?
+   if [ "$test_event_creation_rc" -ne 0 ]; then
+     echo "Test event log creation failed."
+     exit $test_event_creation_rc
+   fi
 fi
 
 
